### PR TITLE
implementing vendor status as attribute text

### PR DESCRIPTION
**Pull request by ChristophCaina**
grafik

### CODE REVIEW

**Comment by ChristophCaina** [comment]
this is closing #62

**Comment by ChristophCaina** [comment]
I've tried to implement more status codes for the vendor status.
The main problem is, that we do have multiple values that can be returned and some of the error codes have different meaning, depending on the inverter and the firmware version.

The main issue: Different codes are being used for three phase inverters as well as for single phase inverters with different meaning.

To implement a correct error mapping, it would be required to detect if the inverter is a single phase or three phase device - as well, what firmware version is running on the device.
Then, we could map the specific error codes correctly.

example:

if(inverter = threephase)
  if(firmware > 3.18)
     use "map1"
  else
    use "map2"
else
  if (firmware > 3.18)
    use "map3"
  else
    use "map4"
    
So, a single phase Inverter with Firmware <= 3.18.x can return `96,98`
A single phase Inverter with Firmware >= 3.19 can return `18x60/18x62`
Both errors are `IslandingTrip1/2`

For the three phase inverter, 96, 97 and 98 are the same as 91, 92, 93 
   `96: AC Over Current L1,`
   `97: AC Over Current L2,`
   `98: AC Over Current L3,`
When running on a Firmware <= 3.18.x
For Inverters running >= 3.19
`8x3A/8x3B/8x3C`
and
`8x3F/ 8x40/8x41`

although, I do have an Inverter with Firmware 4.15.x and the status vendor codes I have received seems to be:
56 --> only mapped to single inverter
83 and 86 --> only mapped to three phase inverters with Firmware <= 3.18.x

SolarEdge Support does not have any other document with error codes mapping.
The linked document may not include all error codes...

So getting a valid status back might nearly be impossible... and with available information, it seems hard to verify the correct error cores.

**Comment by binsentsu** [comment]
Would try to prevent conditions regarding firmware version, as this will become dreadful regarding maintenance. People can always consult the solaredge documentation for details. Think the list you added so far in this PR is already a big improvement for most cases.

**Comment by ChristophCaina** [comment]
the problem is in fact the solaredge documentation at all.
I had a chat with the support and it seems that the documentation is most probably outdated and for sure not complete.

For example, I had some error codes in the status vendor, which I could not find in the documentation - at least, not for the installed inverter and firmware.
After consulting the support, it seems that status codes for other inverters COULD be valid, too...

therefore, I am questioning the usability of the status-vendor information at all...

**Pull request closed without merging**
