### PR TITLE
Add storedge control

### PR DESCRIPTION
**Pull request by mpredfearn**
This PR implements #36 - creating Number and Select entities to allow the user to change the battery charge / discharge profiles. These can be changed via the UI or automation, depending upon individual requirements.
This builds upon my changes to monitor the battery status in #35.

### CODE REVIEW

**Comment by nerfherder** [comment]
Great work, I have merged this into my branch and it is working well.

Another thing I have been playing with is export limit. I am running an automation so if the wholesale price goes negative from my retailer (amber electric, Australia). I can export limit to 0, now that you have done the hard work puttin this in place it wouldn't take much more to add this control in.

**Comment by mpredfearn** [comment]
@nerfherder sure, that should be possible - now that we have the "number" class defined, it should be easy to add the additional registers. Specifically which registers do you need? I could add another commit to add them.

**Comment by binsentsu** [comment]
@nerfherder Thanks for this one. Mayb better to remove the stubs now entirely to eliminate future discussion about them being useless in deployment :) I only have a single inverter at home, so will start with pulling this one in. Do you have feedback on the usage of pymodbusTCP.client iso pymodbus.client as proposed in #39 ?

**Comment by nerfherder** [comment]
@mpredfearn The export limit control is defined on pages 15 and 16 of https://www.photovoltaikforum.com/core/attachment/88445-power-control-open-protocol-for-solaredge-inverters-pdf/.

There are a few intialisation steps described there which I did manually with the mtcp app on iphone.
image

After that is done you can set export limits by writing to E002/F702 with a Float32 value.

image

**Comment by mpredfearn** [comment]
@binsentsu sure, I will adapt my PR to drop the stubs.
I have not tested the changes from #39 in my own system yet, but the change seems good. As you proposed, let's get this merged first then @nerfherder can rebase that change on top :-).

**Comment by mpredfearn** [comment]
@nerfherder Thanks for the details. If it's OK with you I'd like to try to get this support merged first, then I will add a commit later to add support for the export control block.

**Comment by nerfherder** [comment]
@mpredfearn yeah no worries, let's do it as a seperate one

**Comment by mpredfearn** [comment]
Just a couple of minor fixups. Ready for review and hopefully merge :crossed_fingers:

**Comment by WillCodeForCats** [comment]
The control stuff is a pretty extensive addition, someone better at Python than me might have to figure out how to make that work with a multiple inverter system. I can work with Python out of necessity because I'm forced to with homeassistant, but I don't work in it otherwise.

Battery status looks easy enough to port to multiple inverters.

**Comment by binsentsu** [comment]
@mpredfearn Looks good to me. Nice effort! Is there any modbus documentation reference we could add in the readme for battery stuff? The one I referenced from SolarEdge doesn't say a word about batteries :)

**Comment by nerfherder** [comment]
[Power Control Open Protocol for SolarEdge Inverters.pdf](https://github.com/binsentsu/home-assistant-solaredge-modbus/files/7181228/Power.Control.Open.Protocol.for.SolarEdge.Inverters.pdf)

@binsentsu I found it on the photovoltaikforum website, it isn't hosted on the solaredge website - they ask you to contact support to get a hold of it.

https://www.photovoltaikforum.com/core/attachment/88445-power-control-open-protocol-for-solaredge-inverters-pdf/

**Comment by mpredfearn** [comment]
@binsentsu I Used the doc that @nerfherder pointed me to (above) as reference for the implementation. Agreed it would be nice to add some stuff about batteries, and also control of the storedge interface into the Readme. Is that something you want me to add to this PR?

**Comment by binsentsu** [comment]
@mpredfearn if it's possible, that would be great. Together with a link to above pdf.

**Comment by mpredfearn** [comment]
@binsentsu done :-)

**Comment by binsentsu** [comment]
Thanks!

**Pull request merged**
