### PR TITLE
Add modbus address selection

### PR DESCRIPTION
**Pull request by cabeljunky**
Not all the inverters are on the default address 1. 
If a users has more device on the modbus network the mandatory address 1 is not the preferred and can mess up the network.

The change contains the option to select the address in the flow setup.
Then is is saved and is used in all the all the places where the unit was set.

Also this will also make it easier to configure multiple SolarEdge converters.

### CODE REVIEW

**Comment by WillCodeForCats** [comment]
This approach will only work for systems where every inverter has an individual modbus/tcp connection or for single inverter systems.

This will conflict with #12 or #47 where multiple inverters are read in sequence through a single modbus/tcp connection. Inverters chained through the RS-485 bus cannot be read by duplicating the integration since the solaredge inverter only allows one active modbus/tcp connection at a time, so eventually you will end up with overlapping connection attempts (and failures) trying poll a single IP. You could do a configurable base address and iterate upwards from that, but the only reliable way to read a chain of inverters is by iterating through on a single connection.

**Comment by cabeljunky** [comment]
Well this can be combined with the feature #12 and #47. 
The main issue that you have there is that you also your fixed index of 1. And if your inverter is not on that address you can't use your module.

So if you look at the feature #12 
```python
def read_modbus_data_inverters(self):
        for inverter_index in range(self.number_of_inverters):
            inverter_prefix = "i" + str(inverter_index + 1) + "_"
            inverter_data = self.read_holding_registers(unit=inverter_index + 1, address=40071, count=38)
```            
can than be changed to:
```python
def read_modbus_data_inverters(self):
        for inverter_index in range(self.number_of_inverters):
            inverter_prefix = "i" + str(inverter_index + self._address) + "_"
            inverter_data = self.read_holding_registers(unit=inverter_index + self._address, address=40071, count=38)
 ```

**Comment by ctrl-alt-d** [comment]
You save my day! How to vote to this PR will be merged? It runs like a charm.

**Comment by cabeljunky** [comment]
Hello @WillCodeForCats,

Did you had time to check the change? 
Or do you still have concerns

**Comment by WillCodeForCats** [comment]
> Hello @WillCodeForCats,
> 
> Did you had time to check the change? Or do you still have concerns

@cabeljunky Sorry for the very delayed response. I am no longer using this integration, I've moved on to a different one.

**Pull request merged**
